name: insar_cpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - gdal
  - rasterio
  - xarray
  - dask
  - h5py
  - pip
  - pip:
      - isce3  # or local path / wheel if you build it yourself
